# Hello! Welcome to Julia!
#### Julia is a computational language that is growing in popularity amongst the scientfic computing communities. In this notebook we will go through the basics of Markov Chains and Markov Chain Monte Carlo.

#### To begin, lets setup the basics of matrices in Julia. We can initialize a matrix in Julia by specifying it's entries as follows. White space stands between entries and semicolons separate lines. 

In [1]:
using LinearAlgebra

In [2]:
A = [0 1/2 1/2; 1/2 1/2 0;1/2 0 1/2]

3×3 Matrix{Float64}:
 0.0  0.5  0.5
 0.5  0.5  0.0
 0.5  0.0  0.5

#### To multiply matrices, simply use the * command. To find eigenvalues and eigenvectors of A, use eigals(A) and eigvects(A). To tanspose, we use transpose(A).

In [3]:
println("Matrix Multiplication gives:")
println(A*A)
println("The eigenvalues are:")
println(eigvals(A))
println("The eigenvectors are:")
println(eigvecs(A))
println("The transpose is:")
println(transpose(A))

Matrix Multiplication gives:
[0.5 0.25 0.25; 0.25 0.5 0.25; 0.25 0.25 0.5]
The eigenvalues are:
[-0.5000000000000004, 0.49999999999999994, 1.0]
The eigenvectors are:
[-0.8164965809277261 -4.440892098500626e-16 0.5773502691896257; 0.4082482904638635 -0.7071067811865471 0.577350269189626; 0.4082482904638624 0.707106781186548 0.5773502691896257]
The transpose is:
[0.0 0.5 0.5; 0.5 0.5 0.0; 0.5 0.0 0.5]


#### Julia is a 1 index language like Matlab. Thus to grab the third eigenvector corresponding to an eigenvalue of 1, we can use eigvecs(A)[:,3] 

In [4]:
B = eigvecs(transpose(A))[:,3]

3-element Vector{Float64}:
 0.5773502691896257
 0.577350269189626
 0.5773502691896257

#### Note that this is a left eigenvector for A, but not a stationary probability measure beacause it is not normalized. To normalize, we simply divide by the sum

In [5]:
invProb = B/sum(B)

3-element Vector{Float64}:
 0.3333333333333333
 0.3333333333333334
 0.3333333333333333

### Note that in this case, there is a unique eigenvector corresponding to an eigenvalue of 1 and all others have magnitude less than 1. 
## Question 1: Draw the transition graph associated with A and justify this using the Perron-Frobenius Theorem 

## Question 2: Translate the following transition graph into a transition matrix and compute the corresponding stationary distributions. What do you see and why?
<img src = "pdfresizer.com-pdf-crop1024_1.jpg" alt = "Transition Graph" width = 200 height = 200>

## It is not always practical to compute all of the eigenvalues and eigenvectors for large matrices. Lets first find a large matrix.

In [15]:
import Random
N = 5000
M = rand(Float64,N,N);
T = zeros(N,N);
for i in 1:N
    T[i,:] = M[i,:]/sum(M[i,:])
end
T;

## Run the next cell if you would like. Notice how long it takes to compute the eigvalues. 

In [ ]:
eigvals(T)

### Luckily this isn't our only option. With high probability, T will give an irreducible aperiodic Markov chain. 

## Question 3: Find the stationary distribution without finding the eigenvectors. If you use a method which depends on the initial vector, generate another random vector to test your algorithim. Feel free to rerun the cell defining T to reinitialize T.

## Of course, in truly big data, even this is too much. On a real world network, there could be billions of possible states. It isn't feasible to store a billion by billion matrix and compute its stationary distributions. We don't actually need to do this. We only need to know our system is a Markov chain which is irreducible and aperiodic. Then the sample averages along our path with coincide with the invariant distribution after some burn-in period. 

In [24]:
using Erdos

## Below we will generate a random regular graph. By this we just mean a graph for which every vertex has the same number of neighbors, in this case 10. Notice how much larger of a network we can now store. 

In [58]:
g = random_regular_graph(100000,10);
age = VertexMap(g, v -> rand(0:100));

## Question 4: Sample from the Markov chain whose transition probabilites are given by $$\frac{1}{\mathbf{num \  neighbors} + 1}$$ for each of the states neighbors and itself. 

## What is the average age with respect to the stationary measure of this Markov chain? What are the possible stationary measures for this Markov chain.

In [38]:
#Comment out the lines below to get you started
#burn_in = 
#total_per_run = 
# a = rand(vertices(g)) #This will generate a random initial vertex
# age_curr = age[a] #This is how you access the age of a vertex you currently have
